# this is an extra yaml that we require
# when using our build machine
- scope: process
  name: "template"
  automated_mount: False
  docker_run_as_user: True
  environment_docker:
      "-v": ["/nexus:/nexus"]